export { ReactComponent as CoinbaseWalletIcon } from "./CoinbaseWallet.svg";
export { ReactComponent as MetamaskIcon } from "./Metamask.svg";
export { ReactComponent as PristineSwapLogoDark } from "./PristineSwapLogoDark.svg";
export { ReactComponent as PristineSwapLogoLight } from "./PristineSwapLogoLight.svg";
export { ReactComponent as RabbyIcon } from "./Rabby.svg";
export { ReactComponent as RainbowWalletIcon } from "./RainbowWallet.svg";
export { ReactComponent as SkipConnectLogo } from "./SkipConnectLogo.svg";
export { ReactComponent as TrustWalletIcon } from "./TrustWallet.svg";
export { ReactComponent as WalletConnectIcon } from "./WalletConnect.svg";